spring:
  datasource:
    platform: ${DB_PLATFORM}
    url: jdbc:${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

# Uncomment to see detailed logging output
# logging:
#   level:
#     org.hibernate.SQL: debug
#     org.hibernate.type: trace
#
#     org.springframework.jdbc.core.JdbcTemplate: debug
#     org.springframework.jdbc.core.StatementCreatorUtils: trace
